/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_helmetplusone_android_dosbox_DosboxAndroidCallbacks */

#ifndef _Callbacks_com_helmetplusone_android_dosbox_DosboxAndroidCallbacks
#define _Callbacks_com_helmetplusone_android_dosbox_DosboxAndroidCallbacks

/*   public abstract void callbackVideoRedraw(int, int, int, int); */
#define CALLBACK_VIDEO_REDRAW_NAME "callbackVideoRedraw"
/*     Signature: (IIII)V */
#define CALLBACK_VIDEO_REDRAW_SIGNATURE "(IIII)V"

/*   public abstract android.graphics.Bitmap callbackVideoSetMode(int, int); */
#define CALLBACK_VIDEO_SET_MODE_NAME "callbackVideoSetMode"
/*     Signature: (II)Landroid/graphics/Bitmap; */
#define CALLBACK_VIDEO_SET_MODE_SIGNATURE "(II)Landroid/graphics/Bitmap;"

/*   public abstract void callbackAudioInit(int, int, int, int); */
#define CALLBACK_AUDIO_INIT_NAME "callbackAudioInit"
/*     Signature: (IIII)V */
#define CALLBACK_AUDIO_INIT_SIGNATURE "(IIII)V"

/*   public abstract void callbackAudioWriteBuffer(int); */
#define CALLBACK_AUDIO_WRITE_BUFFER_NAME "callbackAudioWriteBuffer"
/*     Signature: (I)V */
#define CALLBACK_AUDIO_WRITE_BUFFER_SIGNATURE "(I)V"

/*   public abstract short[] callbackAudioGetBuffer(); */
#define CALLBACK_AUDIO_GET_BUFFER_NAME "callbackAudioGetBuffer"
/*     Signature: ()[S */
#define CALLBACK_AUDIO_GET_BUFFER_SIGNATURE "()[S"

/*   public abstract void callbackExit(); */
#define CALLBACK_EXIT_NAME "callbackExit"
/*     Signature: ()V */
#define CALLBACK_EXIT_SIGNATURE "()V"

#endif //_Callbacks_com_helmetplusone_android_dosbox_DosboxAndroidCallbacks
